name: Alec Bishop Photogrpahy
favicon: null
layout_spectrum: 0.8426368529908359
typography_spectrum: 0.7810421602334827
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.3176996062975377
  lightness: 0.12930829031392932
  saturation: 0.4201180492527783
  rhythmicContrast: 0.5283699238207191
purpose: []
